version: '3'
services:
  web:
    build: .
    container_name: 2018-skeleton-web
    image: 2018-skeleton-web:latest
    env_file: .env
    environment:
      - NODE_ENV=production
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
  database:
    build: ./ops/database
    container_name: 2018-skeleton-database
    image: 2018-skeleton-database:lastest
    env_file: ./ops/database/.env
    ports:
      - "5432:5432"
    user:
      postgres
  sessionStore:
    build: ./ops/sessionStore
    container_name: 2018-skeleton-session-store
    image: 2018-skeleton-session-store:lastest
    ports:
      - "11211:11211"